name: Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm install

      - name: Build
        run: |
              npm run docs:build

      - name: deploy
        env:
          LLOneBot_GH_TOKEN: ${{ secrets.LLOneBot_GH_TOKEN }}
        run: |
             bash ./script/deploy.sh
